import { computed, ref } from 'vue'

const savedLanguage = typeof localStorage !== 'undefined' ? localStorage.getItem('site-language') : null
const language = ref(savedLanguage === 'tr' ? 'tr' : 'en')

const messages = {
  en: {
    nav: ['About Us', 'Projects', 'API', 'Pricing', 'Contact', 'FAQ'],
    quote: 'Contact us', navDescription: 'Signal registration management platform', language: 'Language',
    heroEyebrow: 'Signal Registry', heroTitle: 'A governed workspace for signal operations',
    heroText: 'Signal Registry gives organizations one environment for live monitoring, registry administration, and controlled workflow design.',
    about: 'View the platform', contact: 'Contact us',
    overviewEyebrow: 'Platform', overviewTitle: 'From signal records to controlled workflows',
    overviewText: 'Review activity through summaries, charts, and unit tables. Administer registry records, then connect sources and actions in the visual editor.',
    featuresEyebrow: 'Capabilities', featuresTitle: 'Operational control across the signal record lifecycle',
    features: [
      ['Live monitoring', 'Summary cards, trend charts, status, and device information in one operational view.'],
      ['Visual workflows', 'Connect sources, actions, and alerts in a defined editor, without custom code.'],
      ['Data delivery', 'Send information to signal sources. Device location is attached when it is available.'],
      ['Operational reporting', 'Review activity, status changes, and detailed records in a consistent format.'],
      ['Access control', 'Sign-in, account administration, and role-based access. Administrators govern users and sessions.'],
      ['Language support', 'English, Turkish, German, French, Spanish, and Italian. The dashboard can open in the browser’s preferred language.'],
    ],
    dashboardEyebrow: 'Dashboard', dashboardTitle: 'A single view of signal status',
    dashboardText: 'Summary cards, trend charts, status distribution, device tables, and pinned monitors are arranged for the operating team.',
    access: 'Request a briefing', mobileEyebrow: 'Workflow design', mobileTitle: 'A controlled editor for signal workflows',
    mobileText: 'Define each step of a signal workflow and connect it in the editor. Follow how information moves from its source to a monitor or alert.',
    mobileList: ['Connect sources to the steps that process them', 'See how each part of the workflow is related', 'Follow signal activity as it changes'],
    partnership: 'Signal Registry', partnershipTitle: 'One operating model for signal data',
    partnershipText: 'Monitoring, registry administration, and workflow design run in the same platform. Speak with Sinyatek about deployment.',
    getInTouch: 'Contact us', resources: 'About the platform',
    aboutPage: {
      title: 'About — Signal Registry',
      description: 'Signal Registry is Sinyatek’s enterprise platform for signal registration operations, operational reporting, and controlled record administration.',
      eyebrow: 'About us',
      heroTitle: 'Enterprise governance for signal registration',
      heroText: 'Signal Registry is Sinyatek’s platform for organizations that require one controlled environment for record monitoring, operational reporting, and authorized updates.',
      briefing: 'Request a briefing',
      heroNote: 'Defined procedures. Enterprise support.',
      platformLabel: 'Platform',
      platformTitle: 'A single system for registration operations',
      platformText: 'Authorized personnel review record status, channel reports, and individual updates in the same system. Access and deployment are arranged with Sinyatek.',
      viewProject: 'Review the project',
      contact: 'Contact us',
      imageAlt: 'Signal Registry operational system',
      officeAlt: 'Signal Registry corporate environment',
      officeCaption: 'Corporate operating environment',
      enterpriseLabel: 'Enterprise platform',
      intro: ' is Sinyatek’s enterprise platform for the administration of signal registration data, with consistent procedures, controlled access, and a complete record lifecycle.',
      introSecondary: 'Management review and compliance rely on the same source of record. Portfolio status, operational reports, and record updates are maintained in one system.',
      metrics: [
        ['Central operations', 'One system for every team responsible for records'],
        ['Accountable process', 'Each update remains traceable and aligned with policy'],
        ['Access control', 'Role-based authorization and managed sessions'],
      ],
      points: [
        'Management reporting on volume, status, trends, and channel performance',
        'Role-based authorization with session governance',
        'Structured record administration and traceability across environments',
      ],
      modelLabel: 'Governance',
      modelTitle: 'Operating principles',
      cards: [
        ['Operational control', ['Standard procedures for routine and exception work', 'Status available from summary to the individual record', 'Consistent practice across teams and environments', 'Assigned ownership for every update']],
        ['Data governance', ['A defined record lifecycle', 'Traceable amendments', 'Separation of operating environments', 'Common standards for every team']],
        ['Implementation', ['Phased deployment with Sinyatek', 'Approval before any production change', 'Documented operating procedures', 'Security incorporated in the architecture']],
      ],
    },
    projectsPage: {
      title: 'Projects — Signal Registry',
      description: 'Signal Registry is Sinyatek’s enterprise project for controlled signal registration, operational reporting, and authorized record administration.',
      eyebrow: 'The project',
      heroTitle: 'Controlled delivery for signal registration',
      heroText: 'Signal Registry provides authorized visibility of signal records, from management reporting to record-level updates, within one secure operating environment.',
      demo: 'Request a demonstration',
      heroNote: 'Defined procedures. Enterprise support.',
      imageAlt: 'Signal Registry project environment',
      imageCaption: 'A controlled environment for project delivery',
      overviewLabel: 'Signal Registry',
      overviewTitle: 'Project overview',
      overviewLead: 'Signal Registry is Sinyatek’s management system for signal registration data. Authorized users review record summaries, trend and channel reports, the unit register, and individual records in one interface.',
      overviewBody: 'Access to the dashboard, profile, and record pages is controlled. The session is verified continuously, and an invalid session returns the user to sign-in. The principal view presents summary cards, trend charts, channel charts, and a unit register. Views may be arranged as required, and operators can move between data sources such as a central depot or a field cabinet. Access is arranged with Sinyatek.',
      flowLabel: 'Operating sequence',
      flowTitle: 'From sign-in to an approved update',
      steps: [
        { label: 'Sign in', title: 'Authenticated access', text: 'The dashboard, profile, and record pages require a valid session. When the session expires, the user is returned to sign-in.' },
        { label: 'Summary', title: 'Summary cards', text: 'The opening view reports record volume, status, and the data source under review.' },
        { label: 'Reports', title: 'Trend and channel reports', text: 'Trend and channel reports are presented with the summary, so a change is visible before a unit is opened.' },
        { label: 'Register', title: 'From the register to a record', text: 'The unit register lists every unit. It may be sorted or filtered, and a selected row opens the corresponding record.' },
        { label: 'Update', title: 'Update the record', text: 'Connections are presented as nodes and links. An authorized update keeps the related units consistent.' },
      ],
      mock: {
        sessionNote: 'The dashboard, profile, and records require a verified session.',
        signIn: 'Sign in',
        signInHint: 'Use your organizational account',
        workEmail: 'Work email',
        password: 'Password',
        records: 'Records',
        acrossSource: 'For this source',
        active: 'Active',
        source: 'Source',
        live: 'Current',
        depot: 'Depot',
        centralDepot: 'Central depot',
        trend: '7-day trend',
        channels: 'Channels',
        units: 'Units',
        inReview: '1 under review',
        unit: 'Unit',
        status: 'Status',
        recordLinks: 'Record links',
        sourceSelected: 'Source selected',
        selected: 'Selected',
        sourceNode: 'Source',
        input: 'Input',
        trigger: 'Trigger',
        watch: 'Output',
        monitor: 'Monitor',
      },
      units: [
        { name: 'Depot A', status: 'Active', review: false },
        { name: 'Cabinet 12', status: 'Review', review: true },
        { name: 'Field 4', status: 'Active', review: false },
      ],
      engageLabel: 'Next step',
      engageTitle: 'Administration of signal records',
      engageText: 'Signal Registry is Sinyatek’s system for signal registration data. Summaries, reports, the unit register, and record updates are available in one place. Access is arranged with Sinyatek.',
      pricing: 'Review pricing',
      contact: 'Contact us',
      productiveAlt: 'Signal Registry operational view',
    },
    faqPage: {
      title: 'FAQ — Signal Registry',
      description: 'Authorized answers on Signal Registry access, session control, dashboard reporting, and record administration.',
      eyebrow: 'Frequently asked questions',
      heroTitle: 'Guidance on Signal Registry',
      heroText: 'These answers cover access, security, dashboard reporting, and record administration. Further arrangements are made with Sinyatek.',
      contact: 'Contact us',
      heroNote: 'Defined procedures. Enterprise support.',
      imageAlt: 'Signal Registry operating environment',
      figureCaption: 'Authorized operating guidance',
      sectionLabel: 'FAQ',
      sectionTitle: 'Frequently asked questions',
      items: [
        {
          title: 'What is Signal Registry?',
          content: 'Signal Registry is Sinyatek’s enterprise system for the administration of signal registration data. Authorized users review summary reports, trend and channel charts, the unit register, and individual records. The dashboard, profile, and record pages require a valid session.',
        },
        {
          title: 'What does the dashboard present?',
          content: 'The dashboard presents summary cards, trend reports, and channel reports for the source under review. The unit register lists every unit and may be sorted or filtered. Authorized users may move between data sources and arrange the operating view.',
        },
        {
          title: 'How is access controlled?',
          content: 'Access to the dashboard and record pages is governed by sign-in. The session is verified continuously. An invalid or expired session returns the user to sign-in. Account credentials remain the responsibility of the organization. Suspected misuse should be reported to iletisim@sinyatek.com.',
        },
        {
          title: 'How is access or support arranged?',
          content: 'Access, implementation, and operating support for Signal Registry are arranged with Sinyatek through the contact page or at iletisim@sinyatek.com. API and environment arrangements are included in that correspondence.',
        },
      ],
      ctaEyebrow: 'Correspondence',
      ctaTitle: 'Further questions',
      ctaText: 'Onboarding, environment arrangements, and secure access are handled with Sinyatek through a defined path.',
      signals: [
        ['Structured onboarding', 'First deployment and activation are arranged with Sinyatek'],
        ['Technical correspondence', 'Integration and configuration are addressed through a defined path'],
        ['Operating support', 'Procedures for secure and consistent use across teams'],
      ],
      ctaButton: 'Contact us',
    },
  },
  tr: {
    nav: ['Hakkımızda', 'Projeler', 'API', 'Fiyatlandırma', 'İletişim', 'FAQ'],
    quote: 'Bize ulaşın', navDescription: 'Sinyal kayıt yönetim platformu', language: 'Dil',
    heroEyebrow: 'Signal Registry', heroTitle: 'Sinyal operasyonları için yönetişimli bir çalışma alanı',
    heroText: 'Signal Registry, kurumlara canlı izleme, kayıt yönetimi ve kontrollü iş akışı tasarımı için tek bir ortam sunar.',
    about: 'Platformu inceleyin', contact: 'Bize ulaşın',
    overviewEyebrow: 'Platform', overviewTitle: 'Sinyal kayıtlarından kontrollü iş akışlarına',
    overviewText: 'Hareketi özetler, grafikler ve birim tabloları üzerinden inceleyin. Kayıt defterini yönetin; kaynakları ve işlemleri görsel editörde birbirine bağlayın.',
    featuresEyebrow: 'Yetenekler', featuresTitle: 'Sinyal kayıt yaşam döngüsünde operasyonel kontrol',
    features: [
      ['Canlı izleme', 'Özet kartlar, eğilim grafikleri, durum ve cihaz bilgisi tek operasyon görünümünde.'],
      ['Görsel iş akışları', 'Kaynakları, işlemleri ve uyarıları tanımlı bir editörde, özel kod olmadan bağlayın.'],
      ['Veri iletimi', 'Bilgiyi sinyal kaynaklarına gönderin. Cihaz konumu uygun olduğunda eklenir.'],
      ['Operasyonel raporlama', 'Hareketi, durum değişikliklerini ve ayrıntılı kayıtları tutarlı bir biçimde inceleyin.'],
      ['Erişim kontrolü', 'Oturum açma, hesap yönetimi ve rol tabanlı erişim. Yöneticiler kullanıcıları ve oturumları yönetir.'],
      ['Dil desteği', 'İngilizce, Türkçe, Almanca, Fransızca, İspanyolca ve İtalyanca. Dashboard, tarayıcının tercih ettiği dille açılabilir.'],
    ],
    dashboardEyebrow: 'Dashboard', dashboardTitle: 'Sinyal durumunun tek görünümü',
    dashboardText: 'Özet kartlar, eğilim grafikleri, durum dağılımı, cihaz tabloları ve sabitlenen monitörler operasyon ekibi için düzenlenir.',
    access: 'Bilgilendirme talep edin', mobileEyebrow: 'İş akışı tasarımı', mobileTitle: 'Sinyal iş akışları için kontrollü bir editör',
    mobileText: 'Bir sinyal iş akışının her adımını tanımlayın ve editörde birbirine bağlayın. Bilginin kaynaktan izlemeye veya uyarıya nasıl ilerlediğini takip edin.',
    mobileList: ['Kaynakları veriyi işleyen adımlara bağlayın', 'İş akışındaki parçaların ilişkisini görün', 'Sinyal hareketini değiştikçe takip edin'],
    partnership: 'Signal Registry', partnershipTitle: 'Sinyal verisi için tek işletim modeli',
    partnershipText: 'İzleme, kayıt yönetimi ve iş akışı tasarımı aynı platformda yürür. Kurulum için Sinyatek ile görüşün.',
    getInTouch: 'Bize ulaşın', resources: 'Platform hakkında',
    aboutPage: {
      title: 'Hakkımızda — Signal Registry',
      description: 'Signal Registry, Sinyatek’in sinyal kayıt operasyonları, operasyonel raporlama ve kontrollü kayıt yönetimi için sunduğu kurumsal platformdur.',
      eyebrow: 'Hakkımızda',
      heroTitle: 'Sinyal kayıtlarında kurumsal yönetişim',
      heroText: 'Signal Registry, kayıt izleme, operasyonel raporlama ve yetkili güncellemeler için kurumlara tek bir kontrollü ortam sunan Sinyatek platformudur.',
      briefing: 'Görüşme talep edin',
      heroNote: 'Tanımlı prosedürler. Kurumsal destek.',
      platformLabel: 'Platform',
      platformTitle: 'Kayıt operasyonları için tek sistem',
      platformText: 'Yetkili personel kayıt durumunu, kanal raporlarını ve tekil güncellemeleri aynı sistemde inceler. Erişim ve kurulum Sinyatek ile planlanır.',
      viewProject: 'Projeyi inceleyin',
      contact: 'Bize ulaşın',
      imageAlt: 'Signal Registry operasyon sistemi',
      officeAlt: 'Signal Registry kurumsal çalışma ortamı',
      officeCaption: 'Kurumsal çalışma ortamı',
      enterpriseLabel: 'Kurumsal platform',
      intro: ', Sinyatek’in sinyal kayıt verisini tutarlı prosedürler, kontrollü erişim ve eksiksiz bir kayıt yaşam döngüsü ile yöneten kurumsal platformudur.',
      introSecondary: 'Yönetim incelemesi ve uyum aynı kayıt kaynağına dayanır. Portföy durumu, operasyon raporları ve kayıt güncellemeleri tek sistemde tutulur.',
      metrics: [
        ['Merkezi operasyon', 'Kayıtlardan sorumlu her ekip için tek sistem'],
        ['Hesap verebilir süreç', 'Her güncelleme izlenebilir ve politika ile uyumludur'],
        ['Erişim kontrolü', 'Rol bazlı yetkilendirme ve yönetilen oturumlar'],
      ],
      points: [
        'Hacim, durum, eğilim ve kanal performansına ilişkin yönetim raporlaması',
        'Oturum yönetişimi ile rol bazlı yetkilendirme',
        'Ortamlar arasında yapılandırılmış ve izlenebilir kayıt yönetimi',
      ],
      modelLabel: 'Yönetişim',
      modelTitle: 'İşletim esasları',
      cards: [
        ['Operasyonel kontrol', ['Rutin ve istisna işler için standart prosedürler', 'Özetten tekil kayda kadar erişilebilir durum', 'Ekipler ve ortamlar arasında tutarlı uygulama', 'Her güncelleme için atanmış sorumluluk']],
        ['Veri yönetişimi', ['Tanımlı kayıt yaşam döngüsü', 'İzlenebilir değişiklikler', 'Operasyon ortamlarının ayrımı', 'Tüm ekipler için ortak standartlar']],
        ['Uygulama', ['Sinyatek ile aşamalı kurulum', 'Üretim değişikliğinden önce onay', 'Yazılı operasyon prosedürleri', 'Mimariye dahil güvenlik']],
      ],
    },
    projectsPage: {
      title: 'Projeler — Signal Registry',
      description: 'Signal Registry, Sinyatek’in kontrollü sinyal kaydı, operasyonel raporlama ve yetkili kayıt yönetimi için yürüttüğü kurumsal projedir.',
      eyebrow: 'Proje',
      heroTitle: 'Sinyal kaydında kontrollü uygulama',
      heroText: 'Signal Registry, sinyal kayıtlarının yönetim raporlamasından kayıt düzeyindeki güncellemelere kadar yetkili görünürlüğünü tek bir güvenli işletim ortamında sunar.',
      demo: 'Tanıtım talep edin',
      heroNote: 'Tanımlı prosedürler. Kurumsal destek.',
      imageAlt: 'Signal Registry proje ortamı',
      imageCaption: 'Proje uygulaması için kontrollü ortam',
      overviewLabel: 'Signal Registry',
      overviewTitle: 'Proje özeti',
      overviewLead: 'Signal Registry, Sinyatek’in sinyal kayıt verisi için yönetim sistemidir. Yetkili kullanıcılar kayıt özetlerini, eğilim ve kanal raporlarını, birim listesini ve tekil kayıtları tek arayüzde inceler.',
      overviewBody: 'Panele, profile ve kayıt sayfalarına erişim kontrollüdür. Oturum sürekli doğrulanır; geçersiz oturum kullanıcıyı giriş ekranına döndürür. Ana görünüm özet kartları, eğilim grafiklerini, kanal grafiklerini ve birim listesini içerir. Görünümler ihtiyaca göre düzenlenebilir; operatörler merkez depo veya saha kabini gibi veri kaynakları arasında geçiş yapabilir. Erişim Sinyatek ile planlanır.',
      flowLabel: 'İşletim sırası',
      flowTitle: 'Girişten onaylı güncellemeye',
      steps: [
        { label: 'Oturum', title: 'Yetkili erişim', text: 'Panel, profil ve kayıt sayfaları geçerli bir oturum gerektirir. Oturum sona erdiğinde kullanıcı giriş ekranına döner.' },
        { label: 'Özet', title: 'Özet kartlar', text: 'Açılış görünümü kayıt hacmini, durumu ve incelenen veri kaynağını bildirir.' },
        { label: 'Raporlar', title: 'Eğilim ve kanal raporları', text: 'Eğilim ve kanal raporları özete eşlik eder; bir değişiklik, birim açılmadan önce görünür.' },
        { label: 'Liste', title: 'Listeden kayda', text: 'Birim listesi tüm birimleri gösterir. Liste sıralanabilir ve filtrelenebilir; seçilen satır ilgili kaydı açar.' },
        { label: 'Güncelleme', title: 'Kaydı güncelleme', text: 'Bağlantılar düğüm ve hat olarak gösterilir. Yetkili güncelleme, ilgili birimlerin tutarlılığını korur.' },
      ],
      mock: {
        sessionNote: 'Panel, profil ve kayıtlar doğrulanmış bir oturum gerektirir.',
        signIn: 'Oturum açın',
        signInHint: 'Kurumsal hesabınızı kullanın',
        workEmail: 'İş e-postası',
        password: 'Parola',
        records: 'Kayıtlar',
        acrossSource: 'Bu kaynak için',
        active: 'Aktif',
        source: 'Kaynak',
        live: 'Güncel',
        depot: 'Depo',
        centralDepot: 'Merkez depo',
        trend: '7 günlük eğilim',
        channels: 'Kanallar',
        units: 'Birimler',
        inReview: '1 incelemede',
        unit: 'Birim',
        status: 'Durum',
        recordLinks: 'Kayıt bağlantıları',
        sourceSelected: 'Kaynak seçili',
        selected: 'Seçili',
        sourceNode: 'Kaynak',
        input: 'Girdi',
        trigger: 'Tetikleyici',
        watch: 'Çıktı',
        monitor: 'İzleme',
      },
      units: [
        { name: 'Depo A', status: 'Aktif', review: false },
        { name: 'Kabin 12', status: 'İnceleme', review: true },
        { name: 'Saha 4', status: 'Aktif', review: false },
      ],
      engageLabel: 'Sonraki adım',
      engageTitle: 'Sinyal kayıtlarının yönetimi',
      engageText: 'Signal Registry, Sinyatek’in sinyal kayıt verisi için sunduğu sistemdir. Özetler, raporlar, birim listesi ve kayıt güncellemeleri tek yerde sunulur. Erişim Sinyatek ile planlanır.',
      pricing: 'Fiyatlandırmayı inceleyin',
      contact: 'Bize ulaşın',
      productiveAlt: 'Signal Registry operasyon görünümü',
    },
    faqPage: {
      title: 'SSS — Signal Registry',
      description: 'Signal Registry erişimi, oturum kontrolü, dashboard raporlaması ve kayıt yönetimi hakkında yetkili yanıtlar.',
      eyebrow: 'Sık sorulan sorular',
      heroTitle: 'Signal Registry hakkında yönlendirme',
      heroText: 'Bu yanıtlar erişim, güvenlik, dashboard raporlaması ve kayıt yönetimini kapsar. İlave düzenlemeler Sinyatek ile yapılır.',
      contact: 'Bize ulaşın',
      heroNote: 'Tanımlı prosedürler. Kurumsal destek.',
      imageAlt: 'Signal Registry işletim ortamı',
      figureCaption: 'Yetkili işletim yönlendirmesi',
      sectionLabel: 'SSS',
      sectionTitle: 'Sık sorulan sorular',
      items: [
        {
          title: 'Signal Registry nedir?',
          content: 'Signal Registry, Sinyatek’in sinyal kayıt verisinin yönetimi için sunduğu kurumsal sistemdir. Yetkili kullanıcılar özet raporları, eğilim ve kanal grafiklerini, birim listesini ve tekil kayıtları inceler. Dashboard, profil ve kayıt sayfaları geçerli bir oturum gerektirir.',
        },
        {
          title: 'Dashboard neleri sunar?',
          content: 'Dashboard, incelenen kaynağa ait özet kartları, eğilim raporlarını ve kanal raporlarını sunar. Birim listesi tüm birimleri içerir; sıralanabilir ve filtrelenebilir. Yetkili kullanıcılar veri kaynakları arasında geçiş yapabilir ve işletim görünümünü düzenleyebilir.',
        },
        {
          title: 'Erişim nasıl kontrol edilir?',
          content: 'Dashboard ve kayıt sayfalarına erişim oturum açma ile yönetilir. Oturum sürekli doğrulanır. Geçersiz veya süresi dolmuş bir oturum kullanıcıyı oturum açma sayfasına döndürür. Hesap bilgilerinin korunması kurumun sorumluluğundadır. Şüpheli kullanım iletisim@sinyatek.com adresine bildirilmelidir.',
        },
        {
          title: 'Erişim veya destek nasıl düzenlenir?',
          content: 'Signal Registry için erişim, uygulama ve işletim desteği iletişim sayfası veya iletisim@sinyatek.com üzerinden Sinyatek ile planlanır. API ve ortam düzenlemeleri bu yazışmanın kapsamındadır.',
        },
      ],
      ctaEyebrow: 'Yazışma',
      ctaTitle: 'İlave sorular',
      ctaText: 'İlk kurulum, ortam düzenlemeleri ve güvenli erişim, tanımlı bir yol üzerinden Sinyatek ile yürütülür.',
      signals: [
        ['Yapılandırılmış kurulum', 'İlk dağıtım ve etkinleştirme Sinyatek ile planlanır'],
        ['Teknik yazışma', 'Entegrasyon ve yapılandırma tanımlı bir yol üzerinden ele alınır'],
        ['İşletim desteği', 'Ekipler arasında güvenli ve tutarlı kullanım prosedürleri'],
      ],
      ctaButton: 'Bize ulaşın',
    },
  },
}

export function documentMeta(routeName) {
  const pages = messages[language.value]
  const page = routeName === 'about'
    ? pages.aboutPage
    : routeName === 'projects'
      ? pages.projectsPage
      : routeName === 'faq'
        ? pages.faqPage
        : null
  if (!page) return null
  return { title: page.title, description: page.description }
}

export function useLanguage() {
  const t = computed(() => messages[language.value])
  function setLanguage(value) {
    language.value = value === 'tr' ? 'tr' : 'en'
    if (typeof localStorage !== 'undefined') localStorage.setItem('site-language', language.value)
    if (typeof document !== 'undefined') document.documentElement.lang = language.value
  }
  return { language, t, setLanguage }
}
